import { baseUrl } from '../lib/utils/constants.js';
import { Toaster } from "react-hot-toast";
import axios from "axios";

import "./globals.css";
import "@/lib/styles/app.css"
import Providers from "../lib/redux/provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

axios.defaults.baseURL = `${baseUrl}/api`;
axios.defaults.withCredentials = true;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
